name: corsa_openeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - numpy
  - matplotlib
  - onnxruntime
  - rasterio
  - ipyleaflet
  - tqdm
  - pip
  - pip:
    - openeo==0.27
    - joblib==1.3.2
    - scikit-learn
    - pyproj
    - ipykernel